- components/BreadCrumb.vue
- components/MainVideo.vue
-
-
-
**Issue(s) this PR closes**: #64
> Round Corners of Video - Issue: #64

- components/BreadCrumb.vue
-
-
-
**Issue(s) this PR closes**: #63
> Fix Breadcrumb - Issue:#63

- static/services/amazon_aurora.json
- static/services/amazon_timestream.json
- static/services/cloudendure_migration.json
-
-
-
**Issue(s) this PR closes**: #71
> Added Missing Service Files - Issue #71

- layouts/default.vue
-
-
-
**Issue(s) this PR closes**: #72
> Add Google Analytics - Issue: #72

- nuxt.config.js
- package-lock.json
- package.json
-
-
-
**Issue(s) this PR closes**: #73
> Added Robots.txt - Issue: #73

- layouts/default.vue
-
-
-
**Issue(s) this PR closes**: #84
> Links to Legal Stuff - Issue: #84

- pages/_category/_name.vue
-
-
-
**Issue(s) this PR closes**: #87
> Same Ads - Issue #87

- pages/_category/_name.vue
-
-
-
**Issue(s) this PR closes**: #82
> Added Service Description - Issue: #82

- static/service_server.js
-
-
-
**Issue(s) this PR closes**: #83
> Building Error Fix Final - Issue: #83

- layouts/error.vue
- pages/_category/_name.vue
- pages/_category/index.vue
-
-
-
**Issue(s) this PR closes**: #85
> Added 404 page - Issue: #85

- components/SmallVideo.vue
-  Just changed the :src attribute to point 'thumbnail' computed property.
-  Thumbnails are shown correctly
-  Thumbnails are created on the fly.
-
**Issue(s) this PR closes**: #102
> Fix Thumbnail Preview - Issue: #102

- pages/_category/_name/_video.vue
- pages/_category/_name/index.vue
-  Redo identical ad size fix.
-
-
-
**Issue(s) this PR closes**: #87
> Identical Ad Fixes - Issue: #87

- pages/_category/_name/_video.vue
- pages/_category/_name/index.vue
-
-
-
**Issue(s) this PR closes**: #106
> Set Video Title to Page Title - Issue: #106

- static/services.json
Dashboard icon for "Internet Of Things" did not work due to a casing typo in the icon URL.
- Icon is displayed correctly
**Issue(s) this PR closes**: #105
> bug: #105 fix fix internet of things icon url

- custom_modules/sitemap-generate.js
- nuxt.config.js
Now all the page URLs are also used for Nuxt static generate mode.
- All the pages are generated on "generate" command, including dedicated video pages.
**Issue(s) this PR closes**: #111
> feat: #111 add generation of static routes

- components/SmallVideo.vue
This PR resolves an issue with invalid relative URL passed inside `SmallVideo` component. This was causing 404 erro when navigating between videos.
- Navigating between videos on service page now occurs without 404 error
**Issue(s) this PR closes**: #111
> bug: #111 fix small-video component invalid video url

- components/BreadCrumb.vue
- utils/text.js
Video ID page is removed from navigation breadcrumbs.
- Video ID is not showing up in breadcrumbs anymore
- Fully rewritten breadcrumbs generation logic for simplicity and predictability
**Issue(s) this PR closes**: Closes #129
> feat: #129 refactor breadcrumbs to match latest routes structure

- components/SmallVideo.vue
Added HTML image `title` attribute for video preview thumbnail with video title.
- Video preview image title attribute contains correct video title
**Issue(s) this PR closes**: Closes #130
> feat: #130 add video preview thumbnails title

- nuxt.config.js
- pages/_category/_name/_video.vue
- pages/_category/_name/index.vue
- pages/_category/index.vue
- pages/index.vue
- plugins/head-generator.js
- services/head-generator/HeadGenerator.js
Created custom head generation plugin to ensure consistency of page meta between pages.
App default meta can be set in `@/plugins/head-generator` and will be used as fallback values on every page.
- Page meta tags are consistent between pages
- Video page `og:image` now contains video thumbnail URL
**Issue(s) this PR closes**: Closes #123
> bug: #123 dynamic head generation service

- components/Ad.vue
- components/Listing.vue
- layouts/default.vue
- pages/_category/_name/index.vue
Improved columns layout for listings grid on mobile and tablet devices
- Service listing grid now contains more readable cards on tablet devices
- Service description is not visible on mobile devices
**Issue(s) this PR closes**: Closes #127
> feat: #127 improve responsiveness of services listing grid

- assets/styles/main.scss
- nuxt.config.js
- package-lock.json
- package.json
Added SCSS into the project with standard way of doing so, using `node-sass` and `sass-loader` development dependencies.
- Now Vue.js component's style tag can be used with attribute `lang="scss"` to process styles with `sass-loader` and compile into CSS during build time.
`npm install` command needs to be called once after this PR changes are pulled.
**Issue(s) this PR closes**: Closes #146
> feat: #146 add scss into the project

- components/SmallVideo.vue
- components/sections/video/MainVideoPlayer.vue
- custom_modules/sitemap-generate.js
- pages/_category/_name/_video.vue
- pages/_category/_name/index.vue
- utils/videos.js
This PR introduces a single place to extract video id and thumbnail for every video and removes such logic from UI components. All the necessary data for every video is being processed during data fetching stage.
- Data flow within the application is simplified and less possibilities for exceptions during render.
**Issue(s) this PR closes**: Closes #143
> feat: #143 refactor video id and thumbnail generation

- components/sections/video/SectionVideoPlayer.vue
This PR provides refactor of `SectionVideoPlayer` component with custom media queries instead of Bootstrap provided grid elements. This gives maximum flexibility to adjust content sizes across different devices.
- Ad column is now present on mobile devices with lesser width
- Columns sizes are now more strict and do not extend with content overflow, which Closes #141 
**Issue(s) this PR closes**: Closes #141 Closes #128
> feat: #128 improve video player section responsiveness

- .gitignore
- nuxt.config.js
- package-lock.json
- package.json
Added [@nuxtjs/pwa](https://pwa.nuxtjs.org/) module that covers existing issues (#162) and provides flexible PWA configuration.  
Note: PWA related features are only working with HTTPS, thus may not be possible to test locally. This related to app install-able on device home screen and service worker caching and offline availability of app assets.
- Service worker is generated and automatically controls offline caching application assets (provides offline mode)
- Manifest is generated to provide PWA configuration and makes application install-able
- Generation of PWA icons needs logo to be added to the project
Note: `npm install` is required for this PR
**Issue(s) this PR closes**: #155 Closes #162
> feat: #162 add nuxt pwa module with minimum config

- nuxt.config.js
Telemetry has been disabled using dedicated Nuxt configuration.
- Telemetry confirmation prompt does not show up during generation anymore
**Issue(s) this PR closes**: Closes #183
> feat: #183 disable Nuxt telemetry

- package.json
Default meta description in `package.json` was not updated, but still used in edge cases for previews, such as Slack. 
- Meta description in `package.json` now same as on every page
**Issue(s) this PR closes**: Closes #182
> bug: #182 fix default description in package json

- components/BreadCrumb.vue
- pages/_category/_name/_video.vue
- pages/_category/_name/index.vue
Breadcrumb component had inconsistent margins on service page and mobile view.
- Margins are now consistent
**Issue(s) this PR closes**: Closes #177
> bug: #177 fix breadcrumbs margins

- components/Ad.vue
- components/Listing.vue
- components/sections/services/ServiceCard/index.vue
- pages/index.vue
This PR includes styles refactor/update for services listing page.  
3 main reasons why previous bootstrap row/column layout was replaced with native CSS grid:
- Bootstrap doesn't provide adequate and configurable solution for fixed sized elements
- Bootstrap doesn't provide extra large media queries that is required for #176 
- Following bootstrap's row/column layout would require trade-offs from UI perspective, including fixed sizes, margins, etc
It was requested in #171 to use "original" size. There is no "original" size, since cads were dynamically sized to match column layout. For now, 260px is selected for cards fixed size. Please, provide feedback if such size looks good for you as well, so we can tune it.
- Dynamic layout is now …
> feat: #171 change services layout to fixed widths

- components/Listing.vue
- components/sections/video/SectionVideoPlayer.vue
- pages/_category/_name/_video.vue
- pages/_category/_name/index.vue
- pages/_category/index.vue
- pages/index.vue
This PR includes a fix for ads not being rendered dynamically in static mode. The issue was dues to previously chosen method behaving differently for SSR and static modes. The issue has been resolved by putting ads shuffling into page data property and applying client only render for ads.
- Ads are not rendered correctly for dev, SSR and static modes
**Issue(s) this PR closes**: Closes #201
> bug: #201 fix ads not rendering dynamically

- README.md
- cli/helpers/text.js
- cli/services/YoutubeClient.js
- cli/videos-search/README.md
- cli/videos-search/cli-options.js
- cli/videos-search/excluded-videos.json
- cli/videos-search/index.js
- package-lock.json
- package.json
This PR introduces Videos Search CLI.  
Check usage examples and full functionality in [README](https://github.com/aws-videos-catalog/avc_website/blob/9276edc530881906acbc5f7f7de5bd5efeb9ea0f/cli/videos-search/README.md)
- Run `npm run cli:videos-search` to run new videos lookup for all the services
- Run `npm run cli:videos-search -- -s ec2` to run new videos lookup for "EC2" service
`npm install` is required after PR is merged
**Issue(s) this PR closes**: Closes #179
> feat: #179 videos search cli
